version: "3.1"

services:
  mindustry:
    image: "thehuntedpie/mindustry:4.0-alpha-56"
    container_name: "mindustry_server"
    hostname: "mindustry-server"
    ports:
      - "6567:6567/tcp" #host-port:internal-port
      - "6567:6567/udp"
    environment:
      - "JAVA_OPTS=-Xms1G -Xmx2G" #set memory limits
    command:
      - "load 1,host" # load save 1 and then host. see help for options
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - "/data/mindustry:/var/lib/mindustry/.mindustry"
