version: "3.1"

services:
  mindustry:
    image: "thehuntedpie/mindustry:4.0-alpha-56"
    container_name: "mindustry_server"
    hostname: "mindustry-server"
    ports:
      - "6567:6567/tcp"
      - "6567:6567/udp"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - "/data/mindustry:/var/lib/mindustry/.mindustry"
